"""backups

The record of every archive taken and what is known about it - P7. Not workspace
scoped: a backup is of the installation, every workspace on it at once.

Revision ID: 74f37035bf6b
Revises: 4c94fe4730fc
Create Date: 2026-08-27 20:25:57.108890

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74f37035bf6b"
down_revision: str | Sequence[str] | None = "4c94fe4730fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "manual",
                "nightly",
                "before_update",
                name="backup_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "ok",
                "unverified",
                "failed",
                name="backup_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("path", sa.String(length=1024), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("contents", sa.JSON(), nullable=False),
        sa.Column("schema_revision", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backups")),
    )
    with op.batch_alter_table("backups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_backups_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backups_status"))

    op.drop_table("backups")
    # ### end Alembic commands ###
