"""contacts

§B5's phonebook - `e164, name, tags, notes`, one number per contact per workspace.
Also the day `conversations.contact_id` becomes a real foreign key: the column was
in the first migration waiting for this table, exactly so this moment is a
constraint and not a backfill.

Revision ID: 0ce9c6dbdf4e
Revises: b4c3c9f44157
Create Date: 2026-08-28 22:15:07.911448

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ce9c6dbdf4e"
down_revision: str | Sequence[str] | None = "b4c3c9f44157"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("e164", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_contacts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint("workspace_id", "e164", name="contact_number"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contacts_e164"), ["e164"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_contacts_workspace_id"), ["workspace_id"], unique=False
        )

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_conversations_contact_id_contacts"),
            "contacts",
            ["contact_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_conversations_contact_id_contacts"), type_="foreignkey"
        )

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contacts_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_contacts_e164"))

    op.drop_table("contacts")
    # ### end Alembic commands ###
