"""assistants

§A6.6's editor, reduced to what an assistant owns: a name, the model behind it, and
the two blocks of text that shape its answers. The eight remaining panels read other
subsystems and arrive with them.

No voice, no speaking speed, no opening lines - those describe a call, and calls are
built last. A column added now would be a promise this table cannot keep.

Revision ID: 0af9260fdde3
Revises: 0ce9c6dbdf4e
Create Date: 2026-08-29 09:53:39.077804

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0af9260fdde3"
down_revision: str | Sequence[str] | None = "0ce9c6dbdf4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("role", sa.String(length=160), nullable=True),
        sa.Column(
            "template",
            sa.Enum(
                "reception",
                "ooh",
                "overflow",
                "blank",
                name="assistant_template",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "paused",
                name="assistant_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("persona", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=12), nullable=True),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_assistants_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistants")),
        sa.UniqueConstraint("workspace_id", "name", name="assistant_name"),
    )
    with op.batch_alter_table("assistants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assistants_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assistants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assistants_workspace_id"))

    op.drop_table("assistants")
    # ### end Alembic commands ###
