"""machine tokens

§B9.1's second and third rows: the inbound webhook and the MCP endpoint each get their
own rotatable credential, separate from the dashboard session, so that a leak of one
does not open the others.

`token_hash` rather than an encrypted column, which is the difference from
`webhooks.secret`: a signing secret has to be readable to sign with, and nothing ever
needs to read one of these back. The unique index is both the lookup every machine
request pays for and the guarantee that two rows cannot share a hash. `last_four`
exists because of the same choice — a value that cannot be read back cannot be masked
on the way out either.

Revision ID: d6f691ad9b67
Revises: 5a103e2f0157
Create Date: 2026-08-31 18:03:35.550640

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6f691ad9b67"
down_revision: str | Sequence[str] | None = "5a103e2f0157"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "machine_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "hooks",
                "mcp",
                name="machine_token_scope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("last_four", sa.String(length=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_machine_tokens_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_machine_tokens")),
    )
    with op.batch_alter_table("machine_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_machine_tokens_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_machine_tokens_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("machine_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_machine_tokens_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_machine_tokens_token_hash"))

    op.drop_table("machine_tokens")
    # ### end Alembic commands ###
