"""webhooks

§B5's row - `url, events[], secret` - plus a name to recognise it by and a switch to
turn it off without losing the secret, because a hook switched off during an incident
should come back without every receiver being reconfigured.

`secret` is an EncryptedStr: encrypted on write, decrypted on read, so no call site
has to remember - and the one that would forget is the one that leaks. `events` is a
JSON list rather than a join table: a vocabulary this codebase already pins, read only
alongside its own row.

No deliveries and no retries. This records what a webhook is; what happened to one is
a different table with a different lifetime, arriving with the sender.

Revision ID: f6527298d040
Revises: 129ebf2f0592
Create Date: 2026-08-29 12:05:55.319535

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from api.models.encrypted import EncryptedStr

# revision identifiers, used by Alembic.
revision: str = "f6527298d040"
down_revision: str | Sequence[str] | None = "129ebf2f0592"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("events", sa.JSON(), nullable=False),
        sa.Column("secret", EncryptedStr(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_webhooks_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhooks")),
    )
    with op.batch_alter_table("webhooks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webhooks_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webhooks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webhooks_workspace_id"))

    op.drop_table("webhooks")
    # ### end Alembic commands ###
