"""channel settings

A channel's non-secret configuration: which origins may embed the web widget, the
reCAPTCHA site key, the score threshold. Apart from `credentials_encrypted` because
that column is encrypted and rotated, and this one is read on every inbound message -
deciding "is this origin allowed" must not mean decrypting a column first.

**Autogenerate also proposed dropping the default on `assistants.tools`, and that was
removed.** It proposed it because the model did not declare the default its own
migration had written, so alembic read the schema as ahead of the models and offered to
undo it. Shipping that proposal silently reverted the previous migration. The models
declare their defaults now, and `alembic/env.py` compares them as text so the dialect's
quoting cannot make an unchanged default look changed.

`server_default` because the column is NOT NULL and the model default is a Python one:
every installation already has a channel row (the first migration inserts one), so
without it this migration fails everywhere except a fresh checkout.

Revision ID: 0fd029e88034
Revises: da4c5eef64b0
Create Date: 2026-08-29 13:35:57.905162

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fd029e88034"
down_revision: str | Sequence[str] | None = "da4c5eef64b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "settings_json", sa.JSON(), nullable=False, server_default=sa.text("'{}'")
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.drop_column("settings_json")

    # ### end Alembic commands ###
