"""assistant tools

Which of §B7's seven an assistant may reach. A JSON list rather than a join table, for
the reason the webhook events are one: a vocabulary this codebase pins, read only
alongside its own row.

`server_default` is not decoration. The column is NOT NULL, and the model's default is
a Python one - it never reaches a row that already exists. Without this, every
installation with an assistant in it fails this migration, and the one machine that
would not have caught it is a fresh checkout with an empty table.

Revision ID: da4c5eef64b0
Revises: f6527298d040
Create Date: 2026-08-29 12:55:28.518505

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da4c5eef64b0"
down_revision: str | Sequence[str] | None = "f6527298d040"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assistants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tools", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assistants", schema=None) as batch_op:
        batch_op.drop_column("tools")

    # ### end Alembic commands ###
