"""notifications

Revision ID: 4c94fe4730fc
Revises: a56bfbac40ef
Create Date: 2026-08-27 15:42:27.005174

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c94fe4730fc"
down_revision: str | Sequence[str] | None = "a56bfbac40ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "failure",
                "review",
                "missed",
                "system",
                name="notification_category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("needs_decision", sa.Boolean(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "primary_action",
            sa.Enum(
                "resend_notification",
                "retry_webhook",
                "allow_number",
                "edit_rule",
                "set_fallback",
                "open_conversation",
                "none",
                name="notification_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("action_payload", sa.JSON(), nullable=True),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
            name=op.f("fk_notifications_resolved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_notifications_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_needs_decision"), ["needs_decision"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_resolved_at"), ["resolved_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_resolved_at"))
        batch_op.drop_index(batch_op.f("ix_notifications_needs_decision"))
        batch_op.drop_index(batch_op.f("ix_notifications_conversation_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_category"))

    op.drop_table("notifications")
    # ### end Alembic commands ###
