"""auth attempts

Revision ID: 358e2f4c521d
Revises: 43be4f8d704e
Create Date: 2026-08-26 23:15:35.565364

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "358e2f4c521d"
down_revision: str | Sequence[str] | None = "43be4f8d704e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "account", "ip", name="attempt_scope", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column(
            "first_failed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_failed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_attempts")),
        sa.UniqueConstraint("scope", "identifier", "action", name="scope_identifier_action"),
    )
    with op.batch_alter_table("auth_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auth_attempts_locked_until"), ["locked_until"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_attempts_locked_until"))

    op.drop_table("auth_attempts")
    # ### end Alembic commands ###
