"""rules

One row per caller pattern - §B5's `rules` table. An exact E.164 or a prefix ending
in `*`, one of three actions (pass | block | ai), and a note. Unique per workspace
and pattern, so the agent never has to pick between two rows for the same caller.

Revision ID: b4c3c9f44157
Revises: 0287df510f9e
Create Date: 2026-08-28 21:49:35.053084

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4c3c9f44157"
down_revision: str | Sequence[str] | None = "0287df510f9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("e164_or_pattern", sa.String(length=20), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "pass",
                "block",
                "ai",
                name="rule_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_rules_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rules")),
        sa.UniqueConstraint("workspace_id", "e164_or_pattern", name="rule_pattern"),
    )
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rules_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rules_workspace_id"))

    op.drop_table("rules")
    # ### end Alembic commands ###
