"""settings store

Revision ID: a56bfbac40ef
Revises: f5a38f3b38f1
Create Date: 2026-08-27 10:35:38.220495

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from api.models.encrypted import EncryptedStr

# revision identifiers, used by Alembic.
revision: str = "a56bfbac40ef"
down_revision: str | Sequence[str] | None = "f5a38f3b38f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("secret_value", EncryptedStr(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_settings_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint("workspace_id", "key", name="scope_key"),
    )
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_settings_key"), ["key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_settings_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settings_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_settings_key"))

    op.drop_table("settings")
    # ### end Alembic commands ###
