"""auth events

Revision ID: 49b2bd773f9a
Revises: f4e60e5e54a2
Create Date: 2026-08-27 08:25:59.616504

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49b2bd773f9a"
down_revision: str | Sequence[str] | None = "f4e60e5e54a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_events")),
    )
    with op.batch_alter_table("auth_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_events_event"), ["event"], unique=False)
        batch_op.create_index(batch_op.f("ix_auth_events_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_auth_events_event"))

    op.drop_table("auth_events")
    # ### end Alembic commands ###
