"""keys codes and password history

Revision ID: f4e60e5e54a2
Revises: 358e2f4c521d
Create Date: 2026-08-26 23:34:14.337352

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4e60e5e54a2"
down_revision: str | Sequence[str] | None = "358e2f4c521d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "key_challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("challenge", sa.String(length=80), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_key_challenges")),
        sa.UniqueConstraint("challenge", name=op.f("uq_key_challenges_challenge")),
    )
    with op.batch_alter_table("key_challenges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_key_challenges_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_key_challenges_username"), ["username"], unique=False
        )

    op.create_table(
        "auth_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "reset",
                "second_factor",
                name="code_purpose",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts_left", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_codes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_codes")),
    )
    with op.batch_alter_table("auth_codes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auth_codes_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_auth_codes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "password_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_history_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_history")),
    )
    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_password_history_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_keys_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_keys")),
    )
    with op.batch_alter_table("user_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_keys_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_keys_user_id"))

    op.drop_table("user_keys")
    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_history_user_id"))

    op.drop_table("password_history")
    with op.batch_alter_table("auth_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_codes_user_id"))
        batch_op.drop_index(batch_op.f("ix_auth_codes_expires_at"))

    op.drop_table("auth_codes")
    with op.batch_alter_table("key_challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_key_challenges_username"))
        batch_op.drop_index(batch_op.f("ix_key_challenges_expires_at"))

    op.drop_table("key_challenges")
    # ### end Alembic commands ###
