"""core tables

The first migration. Everything §B5 calls painful to add later lands here, because
there is no stored row yet and so it costs nothing today:

1. `workspace_id` on every data table (D-028, replacing the original `user_id`).
   On `messages` and `calls` it is denormalised from the parent conversation: no
   exceptions to remember is what makes the rule enforceable.
2. A full-text index on `messages.text` - built at the bottom of this file, by a
   different mechanism per dialect
3. `numbers.owner` - customer or platform holds the number
4. `calls.billable_seconds` and `provider_cost_micros`, integer micros, never floats
5. `messages.stt_confidence` and `messages.language`, per line
6. `conversations` as the core table, with `calls` as a phone-only extension

**On decision 6 and the seeded channel row.** SPEC B5 asks for `channels` to hold one
row of kind `web` from the first migration. No row is seeded here, and the reason is
D-028: every channel belongs to a workspace, and a fresh database has no workspace to
attach one to. Seeding one would mean seeding a workspace, which contradicts C2's
requirement that a fresh database contains no account until first-run setup creates it.

What decision 6 exists to buy is structural - the `channels` table and its `kind`
enumeration, so that Milestone 3 is a write rather than a redesign - and that is here
in full. The `web` row is created alongside the first workspace, in the first-run path.

Revision ID: 56268f297c2b
Revises:
Create Date: 2026-08-26 22:05:12.798173

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56268f297c2b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column(
            "origin",
            sa.Enum(
                "official",
                "community",
                "planned",
                "mcp",
                name="app_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=32), nullable=True),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apps")),
        sa.UniqueConstraint("slug", name=op.f("uq_apps_slug")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("locale", sa.String(length=12), nullable=False),
        sa.Column(
            "theme",
            sa.Enum("dark", "light", name="theme", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_table(
        "app_installs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["apps.id"],
            name=op.f("fk_app_installs_app_id_apps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_app_installs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_installs")),
        sa.UniqueConstraint("workspace_id", "app_id", name="workspace_app"),
    )
    with op.batch_alter_table("app_installs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_app_installs_app_id"), ["app_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_app_installs_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "web",
                "phone",
                "sms",
                "email",
                "whatsapp",
                "telegram",
                "messenger",
                "instagram",
                "discord",
                "slack",
                name="channel_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("app_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("credentials_encrypted", sa.Text(), nullable=True),
        sa.Column("webhook_secret", sa.String(length=128), nullable=True),
        sa.Column("webhook_path", sa.String(length=255), nullable=True),
        sa.Column("default_language", sa.String(length=12), nullable=True),
        sa.Column("agent_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "disabled",
                "error",
                name="channel_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["app_id"], ["apps.id"], name=op.f("fk_channels_app_id_apps"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_channels_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channels")),
        sa.UniqueConstraint("webhook_path", name=op.f("uq_channels_webhook_path")),
    )
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_channels_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "reception",
                "viewer",
                "invited",
                name="role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_memberships_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("user_id", "workspace_id", name="user_workspace"),
    )
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memberships_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memberships_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "direction",
            sa.Enum(
                "inbound",
                "outbound",
                name="direction",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column(
            "handling",
            sa.Enum(
                "ai",
                "human",
                "blocked",
                name="handling",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("intent", sa.String(length=120), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("state_json", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "closed",
                name="conversation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_conversations_channel_id_channels"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_conversations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversations_channel_id"), ["channel_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_external_id"), ["external_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "numbers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_account_ref", sa.String(length=255), nullable=True),
        sa.Column(
            "owner",
            sa.Enum(
                "customer",
                "platform",
                name="number_owner",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("e164", sa.String(length=20), nullable=False),
        sa.Column("sip_config", sa.JSON(), nullable=True),
        sa.Column("agent_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "disabled",
                name="number_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
            name=op.f("fk_numbers_channel_id_channels"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_numbers_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_numbers")),
    )
    with op.batch_alter_table("numbers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_numbers_e164"), ["e164"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_numbers_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "calls",
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("number_id", sa.Integer(), nullable=True),
        sa.Column("from_e164", sa.String(length=20), nullable=True),
        sa.Column("recording_path", sa.String(length=512), nullable=True),
        sa.Column("billable_seconds", sa.Integer(), nullable=True),
        sa.Column("provider_cost_micros", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_calls_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["number_id"],
            ["numbers.id"],
            name=op.f("fk_calls_number_id_numbers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_calls_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("conversation_id", name=op.f("pk_calls")),
    )
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_calls_from_e164"), ["from_e164"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_calls_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("ts_ms", sa.BigInteger(), nullable=False),
        sa.Column(
            "speaker",
            sa.Enum(
                "caller",
                "agent",
                "human",
                name="speaker",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_whisper", sa.Boolean(), nullable=False),
        sa.Column("stt_confidence", sa.Float(), nullable=True),
        sa.Column("language", sa.String(length=12), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_messages_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_messages_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_messages_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###

    _create_message_search_index()


def downgrade() -> None:
    """Downgrade schema."""
    _drop_message_search_index()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_messages_conversation_id"))

    op.drop_table("messages")
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calls_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_calls_from_e164"))

    op.drop_table("calls")
    with op.batch_alter_table("numbers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_numbers_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_numbers_e164"))

    op.drop_table("numbers")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_external_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_channel_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memberships_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_memberships_user_id"))

    op.drop_table("memberships")
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channels_workspace_id"))

    op.drop_table("channels")
    with op.batch_alter_table("app_installs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_app_installs_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_app_installs_app_id"))

    op.drop_table("app_installs")
    op.drop_table("workspaces")
    op.drop_table("users")
    op.drop_table("apps")
    # ### end Alembic commands ###


# --- Full-text search over messages.text -------------------------------------
#
# SPEC B5 decision 2, and A6.3 calls transcript search the headline feature of the
# conversations list. It is built in the first migration for a specific reason: an
# index added afterwards means the data was all there and the feature was not.
#
# The two dialects do not merely differ in syntax here - they use different mechanisms
# entirely. That is the cost D-029 records, arriving where it was predicted to.


def _create_message_search_index() -> None:
    bind = op.get_bind()

    if bind.dialect.name == "postgresql":
        # `simple` rather than `english` or `german`, on purpose. A language-specific
        # configuration stems words by one language's rules, and this table holds
        # en / de / ar side by side - sometimes inside one conversation, since a caller
        # may switch mid-sentence. Stemming Arabic by German rules is worse than not
        # stemming at all. Per-language indexing waits until `messages.language` has
        # enough real data to justify it.
        op.execute(
            "CREATE INDEX ix_messages_text_fts ON messages "
            "USING GIN (to_tsvector('simple', text))"
        )
        return

    if bind.dialect.name == "sqlite":
        # FTS5 is a separate virtual table shadowing `messages`, not an index on it.
        # `content=` makes it external-content: the text is not stored twice, only the
        # index is, and the triggers below keep the two in step.
        op.execute(
            "CREATE VIRTUAL TABLE messages_fts USING fts5("
            "  text,"
            "  content='messages',"
            "  content_rowid='id'"
            ")"
        )
        # External-content FTS5 tables are not maintained automatically. Without these
        # three triggers the index silently stops matching rows written after it was
        # created: search returns fewer results over time and nothing reports an error.
        op.execute(
            "CREATE TRIGGER messages_fts_insert AFTER INSERT ON messages BEGIN"
            "  INSERT INTO messages_fts(rowid, text) VALUES (new.id, new.text);"
            "END"
        )
        op.execute(
            "CREATE TRIGGER messages_fts_delete AFTER DELETE ON messages BEGIN"
            "  INSERT INTO messages_fts(messages_fts, rowid, text)"
            "  VALUES ('delete', old.id, old.text);"
            "END"
        )
        op.execute(
            "CREATE TRIGGER messages_fts_update AFTER UPDATE ON messages BEGIN"
            "  INSERT INTO messages_fts(messages_fts, rowid, text)"
            "  VALUES ('delete', old.id, old.text);"
            "  INSERT INTO messages_fts(rowid, text) VALUES (new.id, new.text);"
            "END"
        )
        return

    raise RuntimeError(
        f"No full-text implementation for dialect {bind.dialect.name!r}. "
        "Only PostgreSQL and SQLite are supported (D-029)."
    )


def _drop_message_search_index() -> None:
    bind = op.get_bind()

    if bind.dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_messages_text_fts")
    elif bind.dialect.name == "sqlite":
        for trigger in ("messages_fts_update", "messages_fts_delete", "messages_fts_insert"):
            op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
        op.execute("DROP TABLE IF EXISTS messages_fts")
