"""knowledge

§B5's row minus two of its six columns. No `embedding`: no pipeline produces one yet,
and a column that is NULL on every row is a place for the first mistake to hide - it
arrives with the retrieval that reads it. No crawler and no uploads either; both land
on top of this table rather than instead of it.

`assistant_id` is nullable and means "every assistant here" when it is not set, and
`SET NULL` on delete - the opening hours outlive whichever assistant was reading them.

Revision ID: 129ebf2f0592
Revises: 0af9260fdde3
Create Date: 2026-08-29 11:32:22.485012

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "129ebf2f0592"
down_revision: str | Sequence[str] | None = "0af9260fdde3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("assistant_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_knowledge_assistant_id_assistants"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_knowledge_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge")),
    )
    with op.batch_alter_table("knowledge", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_knowledge_assistant_id"), ["assistant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("knowledge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_knowledge_assistant_id"))

    op.drop_table("knowledge")
    # ### end Alembic commands ###
