"""rate counters

A ceiling on things that are allowed. `auth_attempts` counts failures and locks with a
backoff; this counts successes against a limit, and the two do not share a table - a
`failures` column holding something that is not a failure is a column the next reader
has to decode.

One row per bucket, one window. When this has to survive more than one process it
becomes Redis, and this shape is what that replaces.

**Autogenerate also proposed an `alter_column` on `assistants.tools`, and it was
removed.** It wanted to set the server default the column already has: alembic cannot
compare server defaults reliably on SQLite (it says so in the log), so it re-proposes
one on every run. Applying it would rebuild the table through `batch_alter_table` to
change nothing. The models now declare the defaults their migrations wrote, which is
what stops the drift being real - this last one is the tool's blind spot, not the
schema's.

Revision ID: 6448f32e950d
Revises: 0fd029e88034
Create Date: 2026-08-29 17:08:00.322257

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6448f32e950d"
down_revision: str | Sequence[str] | None = "0fd029e88034"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_counters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column(
            "window_started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_counters")),
        sa.UniqueConstraint("bucket", name=op.f("uq_rate_counters_bucket")),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("rate_counters")
    # ### end Alembic commands ###
