"""notification detail

The machine's own words about a failure - an exception message, a provider's error
string - kept apart from the translated sentence and shown as machine output. Nullable,
because most notifications have nothing machine-generated to say.


Revision ID: 242e199c1e4a
Revises: 2601289b0174
Create Date: 2026-08-28 07:00:43.407629

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "242e199c1e4a"
down_revision: str | Sequence[str] | None = "2601289b0174"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("detail", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_column("detail")

    # ### end Alembic commands ###
