"""services

The catalogue's first table - §A6.11's Services tab, and the only prices the assistant
is ever allowed to quote. Tel-Agent ships with none of it: an agent that invents a
price is worse than one that says it does not know.

Three columns carry a decision rather than a value:

* `price_mode` - "on request" is a real answer a business gives, not an unfilled
  field. Inferring it from a null price would let "we have not typed this in yet" be
  spoken as "ask us".
* `price_micros` - integer micros, never a float, per CLAUDE.md. The currency is one
  per workspace and lives in the settings registry (`catalogue.currency`), not on the
  row.
* `bookable` - false does not hide a service. It is still quoted and described, and
  the caller is asked to arrange it with a person, which is what an emergency
  call-out should always do.

The three defaults are server-side as well as ORM-side, so a row written by anything
other than this application still gets them.


Revision ID: 5a103e2f0157
Revises: 6448f32e950d
Create Date: 2026-08-30 00:24:08.453407

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a103e2f0157"
down_revision: str | Sequence[str] | None = "6448f32e950d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("says", sa.Text(), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=True),
        sa.Column(
            "price_mode",
            sa.Enum(
                "fixed",
                "hourly",
                "on_request",
                name="price_mode",
                native_enum=False,
                create_constraint=True,
            ),
            server_default=sa.text("'fixed'"),
            nullable=False,
        ),
        sa.Column("price_micros", sa.BigInteger(), nullable=True),
        sa.Column("performed_by", sa.String(length=120), nullable=True),
        sa.Column("bookable", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_services_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_services_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_services_workspace_id"))

    op.drop_table("services")
    # ### end Alembic commands ###
