import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans, Noto_Sans_Arabic } from "next/font/google";
import { notFound } from "next/navigation";

import "../globals.css";
import { DirectionProvider } from "@/components/ui/direction";
import { LOCALES, getDirection, isLocale } from "@/lib/locales";
import { cn } from "@/lib/utils";

const sans = IBM_Plex_Sans({ subsets: ["latin"], weight: ["400", "500", "600"], variable: "--font-sans" });
const mono = IBM_Plex_Mono({ subsets: ["latin"], weight: ["400", "500"], variable: "--font-mono" });
const arabic = Noto_Sans_Arabic({ subsets: ["arabic"], weight: ["400", "500", "600"], variable: "--font-arabic" });

export const metadata: Metadata = {
  title: "Tel-Agent",
  description: "An agent that answers, on every channel.",
};

/**
 * Applied before first paint, so a light-theme user never sees a dark flash and a
 * reader who collapsed the sidebar never sees it wide for a frame and the page jump
 * as it narrows. Both are attributes on `<html>`; the CSS does the rest.
 */
const SHELL_SCRIPT = `try{var d=document.documentElement;if(localStorage.getItem("od-theme")==="light")d.setAttribute("data-od-theme","light");if(localStorage.getItem("od-rail")==="on")d.setAttribute("data-od-rail","on")}catch(e){}`;

export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();

  const direction = getDirection(locale);

  return (
    // Dark is the designed theme; light is a real second pass, switched by
    // `data-od-theme` rather than generated by inverting the dark one.
    <html
      lang={locale}
      dir={direction}
      className={cn(sans.variable, mono.variable, arabic.variable)}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: SHELL_SCRIPT }} />
      </head>
      <body
        className={cn(
          "text-[14px] leading-[1.45]",
          locale === "ar" && "font-[family-name:var(--font-arabic)]",
        )}
      >
        <DirectionProvider direction={direction}>{children}</DirectionProvider>
      </body>
    </html>
  );
}
