import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans, Noto_Sans_Arabic } from "next/font/google";
import { notFound } from "next/navigation";

import ar from "../../../locales/ar/shell.json";
import de from "../../../locales/de/shell.json";
import en from "../../../locales/en/shell.json";

import "../globals.css";
import { DirectionProvider } from "@/components/ui/direction";
import { LOCALES, getDirection, isLocale } from "@/lib/locales";
import { cn } from "@/lib/utils";

const sans = IBM_Plex_Sans({ subsets: ["latin"], weight: ["400", "500", "600"], variable: "--font-sans" });
const mono = IBM_Plex_Mono({ subsets: ["latin"], weight: ["400", "500"], variable: "--font-mono" });
const arabic = Noto_Sans_Arabic({ subsets: ["arabic"], weight: ["400", "500", "600"], variable: "--font-arabic" });

/** "Tel-Agent" is a locked product name (see CLAUDE.md) and is never translated. */
const META_DESCRIPTIONS: Record<string, string> = { en: en.meta_description, de: de.meta_description, ar: ar.meta_description };

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  return {
    title: "Tel-Agent",
    description: META_DESCRIPTIONS[locale] ?? META_DESCRIPTIONS.en,
  };
}

/** Applied before first paint so a light-theme user never sees a dark flash. */
const THEME_SCRIPT = `try{if(localStorage.getItem("od-theme")==="light")document.documentElement.setAttribute("data-od-theme","light")}catch(e){}`;

export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();

  const direction = getDirection(locale);

  return (
    // Dark is the designed theme; light is a real second pass, switched by
    // `data-od-theme` rather than generated by inverting the dark one.
    <html
      lang={locale}
      dir={direction}
      className={cn(sans.variable, mono.variable, arabic.variable)}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }} />
      </head>
      <body
        className={cn(
          "text-[14px] leading-[1.45]",
          locale === "ar" && "font-[family-name:var(--font-arabic)]",
        )}
      >
        <DirectionProvider direction={direction}>{children}</DirectionProvider>
      </body>
    </html>
  );
}
