"""The database: engine, session lifecycle, and the naming rules migrations depend on.

A leaked connection under load is the failure that only appears in production, so the
session dependency below always closes — on the happy path, on an exception, and on a
client that disconnected mid-request.

Two dialects are supported from the first migration (D-029). They are not
interchangeable at the connection layer, and the differences are handled here in one
place rather than discovered one query at a time:

* **Pooling.** SQLite through `aiosqlite` has no server to pool connections to; the
  pool-size settings are meaningful only for PostgreSQL and are refused rather than
  silently ignored.
* **Foreign keys.** SQLite does not enforce them unless asked, per connection. Without
  the pragma below, `memberships.user_id` would happily point at a user that does not
  exist, and the constraint would be documentation rather than a rule.
"""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

from sqlalchemy import MetaData, event, text
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

from api.config import Settings

logger = logging.getLogger("api.db")

# Every constraint and index gets a predictable name.
#
# This is in the "painful to add later" category. Alembic can only drop a constraint it
# can name, and SQLite cannot alter one at all — it rebuilds the table, which needs the
# names to match. Without a convention the names are generated by the backend, differ
# between the two dialects, and a migration written against one fails against the other.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """The declarative base every model inherits from.

    `Base.metadata` is what Alembic compares the database against, so a model that does
    not reach this metadata is a model migrations cannot see.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# The repository root: the parent of the `api` package.
_ROOT = Path(__file__).resolve().parents[1]


def _is_sqlite(url: str) -> bool:
    return url.startswith("sqlite")


def resolve_url(url: str) -> str:
    """Anchor a relative SQLite path to the repository, not to the working directory.

    `sqlite+aiosqlite:///./tel-agent.db` means "next to wherever this process happened
    to be started", so `uvicorn` launched from one directory and `alembic upgrade head`
    run from another quietly use two different databases - and the symptom is an
    application whose tables do not exist rather than an error naming the cause.

    An absolute URL, and every non-SQLite URL, is returned untouched.
    """
    prefix = "sqlite+aiosqlite:///"
    if not url.startswith(prefix):
        return url

    path = url[len(prefix) :]
    # `:memory:` and an already-absolute path are left alone.
    if not path or path.startswith(":") or Path(path).is_absolute():
        return url

    return f"{prefix}{(_ROOT / path).resolve().as_posix()}"


def create_engine(settings: Settings) -> AsyncEngine:
    """Build the engine for the configured dialect."""
    options: dict[str, Any] = {
        "echo": settings.database_echo,
        # Recycle before a connection can be closed by something in the middle. The
        # symptom otherwise is an intermittent "server closed the connection
        # unexpectedly" that nobody can reproduce.
        "pool_pre_ping": True,
    }

    if not _is_sqlite(settings.database_url):
        options |= {
            "pool_size": settings.database_pool_size,
            "max_overflow": settings.database_max_overflow,
            "pool_timeout": settings.database_pool_timeout,
            "pool_recycle": 1800,
        }

    engine = create_async_engine(resolve_url(settings.database_url), **options)

    if _is_sqlite(settings.database_url):
        _enforce_sqlite_foreign_keys(engine)

    return engine


def _enforce_sqlite_foreign_keys(engine: AsyncEngine) -> None:
    """Turn on foreign key enforcement for every SQLite connection.

    SQLite has it off by default and the setting is per connection, not per database,
    so it has to be applied as connections are made rather than once at startup.
    """

    @event.listens_for(engine.sync_engine, "connect")
    def _set_pragma(dbapi_connection: Any, _: Any) -> None:
        cursor = dbapi_connection.cursor()
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.close()


def create_sessionmaker(engine: AsyncEngine) -> async_sessionmaker[AsyncSession]:
    """Sessions that do not expire attributes on commit.

    With the default, reading any attribute after `commit()` issues another query — and
    in an async session that turns a returned object into a lazy-load error the moment
    it is serialised into a response.
    """
    return async_sessionmaker(
        bind=engine,
        expire_on_commit=False,
        autoflush=False,
    )


@asynccontextmanager
async def session_scope(
    sessionmaker: async_sessionmaker[AsyncSession],
) -> AsyncIterator[AsyncSession]:
    """One session per request, always returned to the pool.

    Rolls back on failure rather than leaving a transaction open behind a connection
    that goes back into the pool — the next request to borrow it would inherit the
    broken transaction.

    **A context manager, deliberately, not a bare async generator.** A caller writing
    `async for session in session_scope(...)` and then raising does *not* throw that
    exception into this function: the generator is left suspended at the `yield` until
    garbage collection, so neither the rollback nor the close ever runs. `async with`
    does throw it back in. That distinction is the difference between this working and
    leaking one connection per failed request.
    """
    session = sessionmaker()
    try:
        yield session
    except Exception:
        await session.rollback()
        raise
    finally:
        await session.close()


async def check_database(engine: AsyncEngine) -> bool:
    """Can we actually reach the database right now?

    Runs a real query rather than inspecting the pool: a pool with idle connections in
    it says nothing about whether the server on the other end is still answering. A
    silently dead dependency is worse than an obviously dead one, which is the whole
    reason `/health` is a deep check.
    """
    try:
        async with engine.connect() as connection:
            await connection.execute(text("SELECT 1"))
    except Exception:
        logger.exception("database health check failed")
        return False
    return True
